// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GameState extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static GameState getRootAsGameState(ByteBuffer _bb) { return getRootAsGameState(_bb, new GameState()); }
  public static GameState getRootAsGameState(ByteBuffer _bb, GameState obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GameState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public KeyState keys(int j) { return keys(new KeyState(), j); }
  public KeyState keys(KeyState obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int keysLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public KeyState.Vector keysVector() { return keysVector(new KeyState.Vector()); }
  public KeyState.Vector keysVector(KeyState.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public PlayerState player() { return player(new PlayerState()); }
  public PlayerState player(PlayerState obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public EnemyState enemies(int j) { return enemies(new EnemyState(), j); }
  public EnemyState enemies(EnemyState obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int enemiesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public EnemyState.Vector enemiesVector() { return enemiesVector(new EnemyState.Vector()); }
  public EnemyState.Vector enemiesVector(EnemyState.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public int level() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int score() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createGameState(FlatBufferBuilder builder,
      int keysOffset,
      int playerOffset,
      int enemiesOffset,
      int level,
      int score) {
    builder.startTable(5);
    GameState.addScore(builder, score);
    GameState.addLevel(builder, level);
    GameState.addEnemies(builder, enemiesOffset);
    GameState.addPlayer(builder, playerOffset);
    GameState.addKeys(builder, keysOffset);
    return GameState.endGameState(builder);
  }

  public static void startGameState(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addKeys(FlatBufferBuilder builder, int keysOffset) { builder.addOffset(0, keysOffset, 0); }
  public static int createKeysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startKeysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPlayer(FlatBufferBuilder builder, int playerOffset) { builder.addOffset(1, playerOffset, 0); }
  public static void addEnemies(FlatBufferBuilder builder, int enemiesOffset) { builder.addOffset(2, enemiesOffset, 0); }
  public static int createEnemiesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEnemiesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addLevel(FlatBufferBuilder builder, int level) { builder.addInt(3, level, 0); }
  public static void addScore(FlatBufferBuilder builder, int score) { builder.addInt(4, score, 0); }
  public static int endGameState(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishGameStateBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedGameStateBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GameState get(int j) { return get(new GameState(), j); }
    public GameState get(GameState obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

