// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class KeyState extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static KeyState getRootAsKeyState(ByteBuffer _bb) { return getRootAsKeyState(_bb, new KeyState()); }
  public static KeyState getRootAsKeyState(ByteBuffer _bb, KeyState obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public KeyState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int key() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean pressed() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createKeyState(FlatBufferBuilder builder,
      int key,
      boolean pressed) {
    builder.startTable(2);
    KeyState.addPressed(builder, pressed);
    KeyState.addKey(builder, key);
    return KeyState.endKeyState(builder);
  }

  public static void startKeyState(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addKey(FlatBufferBuilder builder, int key) { builder.addByte(0, (byte) key, (byte) 0); }
  public static void addPressed(FlatBufferBuilder builder, boolean pressed) { builder.addBoolean(1, pressed, false); }
  public static int endKeyState(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public KeyState get(int j) { return get(new KeyState(), j); }
    public KeyState get(KeyState obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

